load cc acoshf.c -q
load cc airyf.c -q
load cc asinf.c -q
load cc asinhf.c -q
load cc atanf.c -q
load cc atanhf.c -q
load cc bdtrf.c -q
load cc betaf.c -q
load cc cbrtf.c -q
load cc chbevlf.c -q
load cc chdtrf.c -q
load cc clogf.c -q
load cc cmplxf.c -q
load cc constf.c -q
load cc coshf.c -q
load cc dawsnf.c -q
load asm68k deinit.asm
load cc ellief.c -q
load cc ellikf.c -q
load cc ellpef.c -q
load cc ellpkf.c -q
load cc ellpjf.c -q
load cc expf.c -q
load cc exp2f.c -q
load cc exp10f.c -q
load cc expnf.c -q
load cc facf.c -q
load cc fdtrf.c -q
load cc floorf.c -q
load cc fresnlf.c -q
load cc gammaf.c -q
load cc gdtrf.c -q
load cc hypergf.c -q
load cc hyp2f1f.c -q
load cc igamf.c -q
load cc igamif.c -q
load cc incbetf.c -q
load cc incbif.c -q
load cc i0f.c -q
load cc i1f.c -q
load cc ivf.c -q
load cc j0f.c -q
load cc j1f.c -q
load cc jnf.c -q
load cc jvf.c -q
load cc k0f.c -q
load cc k1f.c -q
load cc knf.c -q
load cc logf.c -q
load cc log2f.c -q
load cc log10f.c -q
load cc nbdtrf.c -q
load cc ndtrf.c -q
load cc ndtrif.c -q
load cc pdtrf.c -q
load cc polynf.c -q
load cc powif.c -q
load cc powf.c -q
load cc psif.c -q
load cc rgammaf.c -q
load cc shichif.c -q
load cc sicif.c -q
load cc sindgf.c -q
load cc sinf.c -q
load cc sinhf.c -q
load cc spencef.c -q
load cc sqrtf.c -q
load cc stdtrf.c -q
load cc struvef.c -q
load cc tandgf.c -q
load cc tanf.c -q
load cc tanhf.c -q
load cc ynf.c -q
load cc zetaf.c -q
load cc zetacf.c -q
load cc polevlf.c -q

