/*
 *   This file was automatically generated by version 1.7 of cextract.
 *   Manual editing not recommended.
 *
 *   Created: Sat Mar 25 14:00:41 1995
 */
extern long double logl ( long double );
extern long double expl ( long double );
extern long double cosl ( long double );
extern long double sinl ( long double );
extern long double sqrtl ( long double );
extern long double polevll ( long double, void *, int );
extern long double p1evll ( long double, void *, int );
extern long double gammal ( long double );
extern long double lgaml ( long double );

extern long double fabsl ( long double );
extern long double floorl ( long double );
extern long double frexpl ( long double, int * );
extern long double ldexpl ( long double, int );
extern int isnanl ( long double );
extern int isfinitel ( long double );
extern int signbitl ( long double );
extern long double powl ( long double, long double );
extern long double acoshl ( long double x );
extern long double asinhl ( long double x );
extern long double asinl ( long double );
extern long double acosl ( long double x );
extern long double atanhl ( long double x );
extern long double atanl ( long double );
extern long double atan2l ( long double, long double );
extern long double bdtrcl ( int k, int n, long double p );
extern long double bdtrl ( int k, int n, long double p );
extern long double bdtril ( int k, int n, long double y );
extern long double btdtrl ( long double a, long double b, long double x );
extern long double cbrtl ( long double x );
extern long double chdtrcl ( long double df, long double x );
extern long double chdtrl ( long double df, long double x );
extern long double chdtril ( long double df, long double y );
extern long double coshl ( long double );
extern long double ellpel ( long double );
extern long double ellpkl ( long double );
extern long double elliel ( long double phi, long double m );
extern long double ellikl ( long double phi, long double m );
extern int ellpjl ( long double u, long double m, long double *sn, long double *cn, long double *dn, long double *ph );
extern long double exp10l ( long double x );
extern long double exp2l ( long double x );
extern long double fdtrcl ( int ia, int ib, long double x );
extern long double fdtrl ( int ia, int ib, long double x );
extern long double fdtril ( int ia, int ib, long double y );
extern long double ceill ( long double x );
extern long double gdtrl ( long double a, long double b, long double x );
extern long double gdtrcl ( long double a, long double b, long double x );
extern long double igamil ( long double, long double );
extern long double igamcl ( long double, long double );
extern long double igaml ( long double, long double );
extern long double incbetl ( long double, long double, long double );
extern long double incbil ( long double, long double, long double );
extern long double j0l ( long double );
extern long double y0l ( long double );
extern long double j1l ( long double );
extern long double y1l ( long double x );
extern long double jnl ( int n, long double x );
extern int ldrand ( long double *a );
extern long double log10l ( long double x );
extern long double log2l ( long double x );
extern int mtherr ( char *name, int code );
extern long double nbdtrcl ( int k, int n, long double p );
extern long double nbdtrl ( int k, int n, long double p );
extern long double ndtril ( long double );
extern long double ndtrl ( long double a );
extern long double expx2l ( long double );
extern long double erfcl ( long double );
extern long double erfl ( long double );
extern long double pdtrcl ( int k, long double m );
extern long double pdtrl ( int k, long double m );
extern long double pdtril ( int k, long double y );
extern long double powil ( long double, int );
extern long double sinhl ( long double );
extern long double stdtrl ( int k, long double t );
extern long double stdtril ( int k, long double p );
extern long double tanhl ( long double );
extern long double tanl ( long double );
extern long double cotl ( long double x );
extern long double log1pl ( long double );
extern long double expm1l ( long double );
extern long double cosm1l ( long double x );
extern long double ynl ( int n, long double x );

#if 0
/* Complex functions */
extern void cmovl ( void *x, void *y );
extern long double cabsl ( cmplxl *x );
extern long double hypotl ( long double x, long double y );
extern void caddl ( cmplxl *x, cmplxl *y, cmplxl *z );
extern void csubl ( cmplxl *x, cmplxl *y, cmplxl *z );
extern void cmull ( cmplxl *x, cmplxl *y, cmplxl *z );
extern void cdivl ( cmplxl *x, cmplxl *y, cmplxl *z );
extern void csqrtl ( cmplxl *x, cmplxl *y );
extern void cnegl ( cmplxl *x );
#endif
